Imports System.IO

Public Class frmAppSettings

  '===========================================================================================
  '   
  '   Filename : AppSettings.vb
  '
  '   Description: The Application uses the file RVMSetup.stg, generated by INNO Setup, to
  '                   provide default setup data. It then Defines and mainains application
  '                   level data elements that are saved and read automatically on application
  '                   startup and shutdown in the RVMSettings.ini file.
  '
  '   Called By:  AppInit : Initialise
  '               AppFinal : Finalise
  '
  '   Calls:
  '
  '   Version: 1.0.0
  '
  '   Date: 15 Apr 2017
  '
  '===========================================================================================

  '===========================================================================================
  '          PRIVATE CONSTANTS
  '========================================================================================

  '========================================================================================
  '          PUBLIC CONSTANTS
  '========================================================================================
  Public CStrSettingsFileExt As String = ".stg"
  Public cstrSetupFileName As String = "RVMSetup"
  Public cstrSettingsFileName As String = "RVMSettings"

  '========================================================================================
  '          PRIVATE VARIABLES
  '========================================================================================
  Private fApplicationPath As String
  Private fSetupFileName As String
  Private fSettingsFileName As String
  Private fRVMPath As String
  Private fRVMDataPath As String
  Private fRVMLogsPath As String
  Private fUseLastLog As Boolean = True
  Private SettingsFile As New HUSettingsFile

  '========================================================================================
  '          PUBLIC VARIABLES
  '========================================================================================

  '========================================================================================
  '          PRIVATE ROUTINES
  '========================================================================================

  '========================================================================================
  '          PUBLIC ROUTINES
  '========================================================================================

  '========================================================================================
  '          PROPERTY ROUTINES
  '========================================================================================
  Public Property ApplicationPath() As String

    Get
      Return fApplicationPath
    End Get

    Set(ByVal path As String)
      fApplicationPath = path
    End Set

  End Property 'Public Property fApplicationPath

  '========================================================================================
  Public Property SetupFileName() As String

    Get
      Return fSetupFileName
    End Get

    Set(ByVal FileName As String)
      fSetupFileName = FileName
    End Set

  End Property 'Public Property SetupFileName() As String

  '========================================================================================
  Public Property SettingsFileName() As String

    Get
      Return fSettingsFileName
    End Get

    Set(ByVal FileName As String)
      fSettingsFileName = FileName
    End Set

  End Property 'Public Property SetupFileName() As String

  '========================================================================================
  Public Property RVMPath() As String

    Get
      Return fRVMPath
    End Get

    Set(ByVal path As String)
      fRVMPath = path
    End Set

  End Property 'Public Property RVMPath

  '========================================================================================
  Public Property RVMDataPath() As String

    Get
      Return fRVMDataPath
    End Get

    Set(ByVal path As String)
      fRVMDataPath = path
    End Set

  End Property 'Public Property RVMDataPath

  '========================================================================================
  Public Property RVMLogsPath() As String

    Get
      Return fRVMLogsPath
    End Get

    Set(ByVal path As String)
      fRVMLogsPath = path
    End Set

  End Property 'Public Property RVMLogsPath

  '========================================================================================
  Public Property UseLastLog() As Boolean

    Get
      Return fUseLastLog
    End Get

    Set(ByVal Value As Boolean)
      fUseLastLog = Value
    End Set

  End Property 'Public Property RVMLogsPath

  '========================================================================================
  '          MENU ROUTINES
  '========================================================================================

  '========================================================================================
  '          COMMAND BUTTON ROUTINES
  '========================================================================================
  Private Sub btnBrowse_Click(sender As Object, e As EventArgs) Handles btnBrowse.Click

  End Sub 'Private Sub btnBrowse_Click

  '========================================================================================
  Private Sub btnCancel_Click(sender As Object, e As EventArgs) Handles btnCancel.Click
    Me.Close()
  End Sub 'Private Sub btnCancel_Click

  '========================================================================================
  Private Sub btnHelp_Click(sender As Object, e As EventArgs) Handles btnHelp.Click
    Me.Close()
  End Sub 'Private Sub btnHelp

  '==========================================================================================
  Private Sub btnOK_Click(sender As Object, e As EventArgs) Handles btnOK.Click
    Me.Close()
  End Sub 'Private Sub btnOK_Cli

  '========================================================================================
  '          CONTROL ROUTINES
  '========================================================================================

  '========================================================================================
  '          FILE ROUTINES
  '========================================================================================
  Public Function SetupFileExists() As Boolean

    If My.Computer.FileSystem.FileExists(SetupFileName) Then
      Return True
    Else
      Return False
    End If 'If My.Computer.FileSystem.FileExists

  End Function 'Public Function SetupFileExist

  '----------------------------------------------------------------------------------------
  Public Sub ReadSetupFile()

    Try
      ' Create an instance of Stream Reader to read from a file.
      ' The using statement also closes the Stream Reader.
      Using sr As StreamReader = New StreamReader(SetupFileName)
        Dim line As String
        ' Read lines from the file until the end of
        ' the file is reached.
        line = sr.ReadLine()        'File Version number
        RVMPath = sr.ReadLine()
        RVMDataPath = sr.ReadLine()
        RVMLogsPath = sr.ReadLine()
      End Using
    Catch e As Exception
      'Let the user know what went wrong.
      MessageBox.Show(e.Message)
    End Try

  End Sub 'Public Sub ReadSetupFile

  '========================================================================================
  Public Function SettingsFileExists() As Boolean

    If My.Computer.FileSystem.FileExists(SettingsFileName) Then
      Return True
    Else
      Return False
    End If 'If My.Computer.FileSystem.FileExists

  End Function 'Public Function SettingsFileExist

  '----------------------------------------------------------------------------------------
  Public Sub InstallDefaultSettings()

    UseLastLog = True

  End Sub ' Public Sub InstallDefaultSettings

  '----------------------------------------------------------------------------------------
  Public Function LoadAppSettings() As Boolean

    If Not SettingsFileExists() Then
      MessageBox.Show("No File. loading Default data.")
      InstallDefaultSettings()
      Return False
    End If ' If Not SettingsFileExists

    'MessageBox.Show("loading AppSettings file data.")
    'MessageBox.Show(SettingsFileName)

    'Using AppSettiingsReader As New _
    'Microsoft.VisualBasic.FileIO.TextFieldParser(SettingsFileName)

    Return True







    'End Using ' AppSettiingsReader






    'Try
    ' Create an instance of Stream Reader to read from a file.
    ' The using statement also closes the Stream Reader.
    'Using sr As StreamReader = New StreamReader(SettingsFileName)
    'Dim line As String
    ' Read lines from the file until the end of
    ' the file is reached.
    'line = sr.ReadLine()        'File Version number
    '     RVMPath = sr.ReadLine()
    '    RVMDataPath = sr.ReadLine()
    '   RVMLogsPath = sr.ReadLine()
    'End Using
    'Catch e As Exception
    'Let the user know what went wrong.
    '   MessageBox.Show(e.Message)
    'End Try

  End Function ' Public Function LoadAppSettings

  '----------------------------------------------------------------------------------------
  Public Sub WriteSettingsFile()

    Dim OldSettingsFileName As String

    ' If the file exists then we must rename it before creating a new one
    If SettingsFileExists() Then
      MessageBox.Show("Renaming old Settingsfile.")
      OldSettingsFileName = SetupFileName + "OLD"
      My.Computer.FileSystem.RenameFile(SettingsFileName, OldSettingsFileName)
    End If ' If SettingsFileExists

    Try
      'Create an instance of Stream Writer to read from a file.
      ' The using statement also closes the Stream Writer.
      Using SettingsFile As StreamWriter = New StreamWriter(SettingsFileName)
        Dim line As String
        ' Write records to the file 
        SettingsFile.WriteLine(RVMPath)
        SettingsFile.WriteLine(RVMDataPath)
        SettingsFile.WriteLine(RVMLogsPath)
      End Using
    Catch e As Exception
      'Let the user know what went wrong.
      MessageBox.Show(e.Message)
    End Try

    My.Computer.FileSystem.DeleteFile(OldSettingsFileName)

  End Sub 'Public Sub WriteSettingsFile

  '========================================================================================
  '          FORM ROUTINES
  '========================================================================================
  Private Sub frmAppSettings_Shown(sender As Object, e As EventArgs) Handles MyBase.Shown

    tbxApplicationPath.Text = ApplicationPath
    tbxRVMPath.Text = RVMPath
    tbxRVMDataPath.Text = RVMDataPath
    tbxRVMLogsPath.Text = RVMLogsPath
    chkUseLastLog.Checked = UseLastLog

    '   Dim SettingsFile As New HUSettingsFile
    'MessageBox.Show(SettingsFile.OpenHUTextFile())

  End Sub 'Private Sub frmAppSettings_Shown

  '========================================================================================

End Class 'Public Class frmAppSettings